image: registry.gitlab.com/devteamreims/node-yarn:7.2.0

# cache:
#   untracked: true
#   key: "$CI_BUILD_REF_NAME"
#   paths:
#     - node_modules/

stages:
  - test
  - build
  - deploy

check_deps:
  stage: test
  script:
    - yarn
    - npm run check-deps --silent
  allow_failure: true

lint:
  stage: test
  script:
    - yarn
    - npm run lint -- --quiet

flow:
  stage: test
  script:
    - apt-get update -qq
    - apt-get install -qy libelf1
    - yarn
    - npm run flow

jest:
  stage: test
  script:
    - yarn
    - npm test -- --coverage

build:artifact:
  stage: build
  script:
    - yarn
    - npm run build:ci
  artifacts:
    paths:
      - build/

build_release_image:
  stage: deploy
  image: docker:git
  dependencies:
    - build:artifact
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  only:
    - tags

build_image:
  stage: deploy
  image: docker:git
  dependencies:
    - build:artifact
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  only:
    - master
