// flow-typed signature: 320568368f456ea11d4607eed49230e3
// flow-typed version: <<STUB>>/4me.env_v^0.0.6/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '4me.env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '4me.env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '4me.env/build/clients' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/clients/index' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/clients/specials' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/clients/zone1' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/clients/zone2' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/clients/zone3' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/clusters/index' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/frequencies/index' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/index' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/4E' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/4H' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/4N' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/5R' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/FIR' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/index' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/KD2F' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/RFUE' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/RMS' {
  declare module.exports: any;
}

declare module '4me.env/build/data/LFEE/sector_groups/URMN' {
  declare module.exports: any;
}

declare module '4me.env/build/frequencies' {
  declare module.exports: any;
}

declare module '4me.env/build/index' {
  declare module.exports: any;
}

declare module '4me.env/build/sectors/index' {
  declare module.exports: any;
}

declare module '4me.env/build/sectors/prettyName' {
  declare module.exports: any;
}

declare module '4me.env/test/api' {
  declare module.exports: any;
}

declare module '4me.env/test/clients/api' {
  declare module.exports: any;
}

declare module '4me.env/test/clients/mock/index' {
  declare module.exports: any;
}

declare module '4me.env/test/data/clients' {
  declare module.exports: any;
}

declare module '4me.env/test/data/clusters' {
  declare module.exports: any;
}

declare module '4me.env/test/data/frequencies' {
  declare module.exports: any;
}

declare module '4me.env/test/data/sectorGroups' {
  declare module.exports: any;
}

declare module '4me.env/test/frequencies/api' {
  declare module.exports: any;
}

declare module '4me.env/test/frequencies/mock/index' {
  declare module.exports: any;
}

declare module '4me.env/test/sectors/api' {
  declare module.exports: any;
}

declare module '4me.env/test/sectors/clusters' {
  declare module.exports: any;
}

declare module '4me.env/test/sectors/mock/index' {
  declare module.exports: any;
}

declare module '4me.env/test/sectors/prettyName' {
  declare module.exports: any;
}

declare module '4me.env/test/sectors/sectorGroups' {
  declare module.exports: any;
}

// Filename aliases
declare module '4me.env/build/clients.js' {
  declare module.exports: $Exports<'4me.env/build/clients'>;
}
declare module '4me.env/build/data/LFEE/clients/index.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/clients/index'>;
}
declare module '4me.env/build/data/LFEE/clients/specials.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/clients/specials'>;
}
declare module '4me.env/build/data/LFEE/clients/zone1.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/clients/zone1'>;
}
declare module '4me.env/build/data/LFEE/clients/zone2.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/clients/zone2'>;
}
declare module '4me.env/build/data/LFEE/clients/zone3.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/clients/zone3'>;
}
declare module '4me.env/build/data/LFEE/clusters/index.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/clusters/index'>;
}
declare module '4me.env/build/data/LFEE/frequencies/index.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/frequencies/index'>;
}
declare module '4me.env/build/data/LFEE/index.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/index'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/4E.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/4E'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/4H.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/4H'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/4N.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/4N'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/5R.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/5R'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/FIR.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/FIR'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/index.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/index'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/KD2F.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/KD2F'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/RFUE.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/RFUE'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/RMS.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/RMS'>;
}
declare module '4me.env/build/data/LFEE/sector_groups/URMN.js' {
  declare module.exports: $Exports<'4me.env/build/data/LFEE/sector_groups/URMN'>;
}
declare module '4me.env/build/frequencies.js' {
  declare module.exports: $Exports<'4me.env/build/frequencies'>;
}
declare module '4me.env/build/index.js' {
  declare module.exports: $Exports<'4me.env/build/index'>;
}
declare module '4me.env/build/sectors/index.js' {
  declare module.exports: $Exports<'4me.env/build/sectors/index'>;
}
declare module '4me.env/build/sectors/prettyName.js' {
  declare module.exports: $Exports<'4me.env/build/sectors/prettyName'>;
}
declare module '4me.env/test/api.js' {
  declare module.exports: $Exports<'4me.env/test/api'>;
}
declare module '4me.env/test/clients/api.js' {
  declare module.exports: $Exports<'4me.env/test/clients/api'>;
}
declare module '4me.env/test/clients/mock/index.js' {
  declare module.exports: $Exports<'4me.env/test/clients/mock/index'>;
}
declare module '4me.env/test/data/clients.js' {
  declare module.exports: $Exports<'4me.env/test/data/clients'>;
}
declare module '4me.env/test/data/clusters.js' {
  declare module.exports: $Exports<'4me.env/test/data/clusters'>;
}
declare module '4me.env/test/data/frequencies.js' {
  declare module.exports: $Exports<'4me.env/test/data/frequencies'>;
}
declare module '4me.env/test/data/sectorGroups.js' {
  declare module.exports: $Exports<'4me.env/test/data/sectorGroups'>;
}
declare module '4me.env/test/frequencies/api.js' {
  declare module.exports: $Exports<'4me.env/test/frequencies/api'>;
}
declare module '4me.env/test/frequencies/mock/index.js' {
  declare module.exports: $Exports<'4me.env/test/frequencies/mock/index'>;
}
declare module '4me.env/test/sectors/api.js' {
  declare module.exports: $Exports<'4me.env/test/sectors/api'>;
}
declare module '4me.env/test/sectors/clusters.js' {
  declare module.exports: $Exports<'4me.env/test/sectors/clusters'>;
}
declare module '4me.env/test/sectors/mock/index.js' {
  declare module.exports: $Exports<'4me.env/test/sectors/mock/index'>;
}
declare module '4me.env/test/sectors/prettyName.js' {
  declare module.exports: $Exports<'4me.env/test/sectors/prettyName'>;
}
declare module '4me.env/test/sectors/sectorGroups.js' {
  declare module.exports: $Exports<'4me.env/test/sectors/sectorGroups'>;
}
