// flow-typed signature: 885f50fd5244e49569d23aea5af84a49
// flow-typed version: <<STUB>>/babel-preset-stage-1_v6.13.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-stage-1'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-stage-1' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-stage-1/index' {
  declare module.exports: $Exports<'babel-preset-stage-1'>;
}
declare module 'babel-preset-stage-1/index.js' {
  declare module.exports: $Exports<'babel-preset-stage-1'>;
}
