// flow-typed signature: f76ed2901d013415f598e4d4fe63d57b
// flow-typed version: <<STUB>>/copy-webpack-plugin_v3.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/shouldIgnore' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/toLooksLikeDirectory' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/writeDirectoryToAssets' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/writeFileToAssets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/index'>;
}
declare module 'copy-webpack-plugin/dist/shouldIgnore.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/shouldIgnore'>;
}
declare module 'copy-webpack-plugin/dist/toLooksLikeDirectory.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/toLooksLikeDirectory'>;
}
declare module 'copy-webpack-plugin/dist/writeDirectoryToAssets.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/writeDirectoryToAssets'>;
}
declare module 'copy-webpack-plugin/dist/writeFileToAssets.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/writeFileToAssets'>;
}
