// flow-typed signature: d583e7383b459361bdfa3d226ef4dc76
// flow-typed version: <<STUB>>/flexbox-react_v^4.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flexbox-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flexbox-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flexbox-react/dist/Flexbox' {
  declare module.exports: any;
}

declare module 'flexbox-react/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flexbox-react/dist/Flexbox.js' {
  declare module.exports: $Exports<'flexbox-react/dist/Flexbox'>;
}
declare module 'flexbox-react/dist/index.js' {
  declare module.exports: $Exports<'flexbox-react/dist/index'>;
}
