// flow-typed signature: cdd6fad6dc717c6aa80090776a68d70b
// flow-typed version: <<STUB>>/normalize.css_v5.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
