// flow-typed signature: 1ab68ea647c3bea454bdee62bf40a2e9
// flow-typed version: <<STUB>>/normalize.css_v5.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
