// flow-typed signature: 1a5259c90c80a74412b18e4dc770c11f
// flow-typed version: <<STUB>>/pui-react-tooltip_v^7.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pui-react-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pui-react-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pui-react-tooltip/tooltip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pui-react-tooltip/tooltip.js' {
  declare module.exports: $Exports<'pui-react-tooltip/tooltip'>;
}
