// flow-typed signature: ba8334ef05c1bc7216b98c215ceb137c
// flow-typed version: <<STUB>>/pui-react-overlay-trigger_v^7.3.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pui-react-overlay-trigger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pui-react-overlay-trigger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pui-react-overlay-trigger/overlay-trigger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pui-react-overlay-trigger/overlay-trigger.js' {
  declare module.exports: $Exports<'pui-react-overlay-trigger/overlay-trigger'>;
}
