// flow-typed signature: 519b8c7d58c20b3423f2763c2a1291fc
// flow-typed version: <<STUB>>/react-highlighter_v0.3.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-highlighter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-highlighter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-highlighter/lib/highlighter' {
  declare module.exports: any;
}

declare module 'react-highlighter/lib/regExpPropType' {
  declare module.exports: any;
}

declare module 'react-highlighter/test/testHighlighter' {
  declare module.exports: any;
}

declare module 'react-highlighter/test/testRegExpPropType' {
  declare module.exports: any;
}

declare module 'react-highlighter/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-highlighter/lib/highlighter.js' {
  declare module.exports: $Exports<'react-highlighter/lib/highlighter'>;
}
declare module 'react-highlighter/lib/regExpPropType.js' {
  declare module.exports: $Exports<'react-highlighter/lib/regExpPropType'>;
}
declare module 'react-highlighter/test/testHighlighter.js' {
  declare module.exports: $Exports<'react-highlighter/test/testHighlighter'>;
}
declare module 'react-highlighter/test/testRegExpPropType.js' {
  declare module.exports: $Exports<'react-highlighter/test/testRegExpPropType'>;
}
declare module 'react-highlighter/webpack.config.js' {
  declare module.exports: $Exports<'react-highlighter/webpack.config'>;
}
