// flow-typed signature: c8e59f8949f97c7587c63d335069c79c
// flow-typed version: <<STUB>>/redux-devtools-filter-actions_v1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools-filter-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools-filter-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools-filter-actions/lib/FilterMonitor' {
  declare module.exports: any;
}

declare module 'redux-devtools-filter-actions/lib/index' {
  declare module.exports: any;
}

declare module 'redux-devtools-filter-actions/lib/reducers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools-filter-actions/lib/FilterMonitor.js' {
  declare module.exports: $Exports<'redux-devtools-filter-actions/lib/FilterMonitor'>;
}
declare module 'redux-devtools-filter-actions/lib/index.js' {
  declare module.exports: $Exports<'redux-devtools-filter-actions/lib/index'>;
}
declare module 'redux-devtools-filter-actions/lib/reducers.js' {
  declare module.exports: $Exports<'redux-devtools-filter-actions/lib/reducers'>;
}
